version: '3.5'


services:

  application-backend:
    build: .laminas-ci
    restart: always
    tty: true
    working_dir: /var/www/application
    volumes:
      - .:/var/www/application
    container_name: application-backend


  application-nginx:
    image: nginx:alpine
    container_name: application-nginx
    restart: always
    tty: true
    environment:
      - "APPLICATION_UPSTREAM=application-backend:9000"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/templates/:/etc/nginx/templates/
      - ./public/:/var/www/application/public/
    ports:
      - "80:80"
      - "443:443"